# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mittaukset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aika', models.DateTimeField(auto_now_add=True)),
                ('kosteus', models.DecimalField(decimal_places=2, max_digits=5)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
